# Example OpenAPI spec for testing
# This is a minimal fixture used by tests
openapi: "3.0.0"
info:
  title: "Test API"
  version: "1.0.0"
  description: "Test fixture for API registration tests"
paths:
  /test/hello:
    get:
      operationId: test_hello
      summary: "Hello endpoint"
      responses:
        "200":
          description: "OK"
  /test/echo:
    post:
      operationId: test_echo
      summary: "Echo endpoint"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        "200":
          description: "OK"
