import sys
sys.stdout.reconfigure(encoding='utf-8')
import os
import argparse
from utils import load_env, load_json

def load_specialist(name):
    """Loads the persona context for a specialist."""
    path = f"specialists/{name}.txt"
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    return f"You are {name}, an expert in your field."

import requests

def generate_marketing_copy(agent_name, vertical, tone="Persuasive"):
    # 1. Load Sparkle
    sparkle_context = load_specialist("Sparkle")
    
    print(f"✨ Sparkle: Dreaming up campaigns for '{agent_name}' ({vertical})...")
    
    # 2. Construct Prompt 
    # (Using Mock generation for speed, but structure allows swapping to LLM)
    prompt = f"""
    SYSTEM: {sparkle_context}
    TASK: Create a 3-email sales sequence for {agent_name}.
    VERTICAL: {vertical}
    TONE: {tone}
    """
    
    # In a real scenario, this would call Gemini/Ollama.
    # For now, we simulate Sparkle's output style based on her persona.
    
    print(f"\n[CAMPAIGN GENERATED by SPARKLE]")
    print(f"Subject: ✨ Stop losing {vertical} leads (Use {agent_name})")
    print(f"Body:\nHi [Name],\n\nI see you're struggling with missed calls. That's so 2024.\nMeet {agent_name} - your new AI dispatcher.\n\nShe's fast. She's smart.\n\nLet's chat,\nForge")
    
    return True

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python marketing_generator.py <agent_name> <vertical>")
    else:
        generate_marketing_copy(sys.argv[1], sys.argv[2])
